import Headeruser from "@/components/Headeruser";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Headeruser></Headeruser>
        {children}
      </body>
    </html>
  );
}
